[package]
name = "steel_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.25.8"
tree-sitter-rust = "0.24.0"
tree-sitter-java = "0.23.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
regex = "1.10"

[build-dependencies]
cc = "1.2.36"
